tensor([[ -3.8968,  -0.7224,  -5.3364,  ...,  -7.4604,   4.0949,   3.8612],
        [ -3.5888,  -4.2154,  -1.7239,  ...,  -1.4905,  -0.9701,   5.1199],
        [ -1.6715,  -3.2873,  -1.3467,  ...,  -1.7106,  -1.1049,   3.0178],
        ...,
        [ 12.3509,  10.3758,  21.7202,  ...,   5.9557,   0.4956,   0.9439],
        [ -8.6320,   3.9404,   0.4083,  ..., -10.0381,   1.0375,  -0.4029],
        [ -3.0567,   0.2610,  -0.2628,  ...,  -4.3497,  -1.8391,   6.5126]],
       device='cuda:0', grad_fn=<AddmmBackward>)
tensor([157, 247, 834, 264, 629, 620,   9, 594, 176, 326, 977, 480, 273,  38,
        992,  52, 941, 791, 837, 125, 555, 156,  45, 439,  59, 896,  22, 572,
        903, 237, 278, 891,   6, 649, 683, 332, 433, 682, 753, 661, 875, 622,
        118, 935, 309, 222, 530, 559, 443,  62, 238, 142, 952, 155, 932, 840,
        899, 515,  85, 673, 357, 262, 135, 393, 882,  92, 840, 342, 675,  91,
        154,  27, 552, 272, 388, 587, 332, 518, 316, 468, 344,  85, 975,  29,
        917, 947,  54, 979, 253, 255, 662, 451, 227,  60, 302, 954, 878, 206,
        378, 463, 964, 566, 229, 445,  61, 157, 671, 202, 517,  12,  20, 637,
        741, 265, 900,  53, 484, 307, 976, 456, 313, 454, 749, 335, 232, 394,
        832, 879], device='cuda:0')
/home/naddeok5/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py:446: UserWarning: Using a target size (torch.Size([128])) that is different to the input size (torch.Size([128, 1000])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "vgg_model_trainer.py", line 41, in <module>
    academy.train()
  File "/home/naddeok5/FIM/wandb_academy.py", line 107, in train
    print(criterion(outputs, labels))
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 446, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2659, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/functional.py", line 71, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore
RuntimeError: The size of tensor a (1000) must match the size of tensor b (128) at non-singleton dimension 1
