2021-02-16 13:52:05,285 INFO    MainThread:23347 [wandb_setup.py:_flush():70] setting env: {}
2021-02-16 13:52:05,285 INFO    MainThread:23347 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-16 13:52:05,285 INFO    MainThread:23347 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-16 13:52:05,286 INFO    MainThread:23347 [wandb_init.py:_log_setup():319] Logging user logs to /home/naddeok5/FIM/wandb/run-20210216_135205-yy6x5a1e/logs/debug.log
2021-02-16 13:52:05,286 INFO    MainThread:23347 [wandb_init.py:_log_setup():320] Logging internal logs to /home/naddeok5/FIM/wandb/run-20210216_135205-yy6x5a1e/logs/debug-internal.log
2021-02-16 13:52:05,286 INFO    MainThread:23347 [wandb_init.py:init():324] calling init triggers
2021-02-16 13:52:05,286 INFO    MainThread:23347 [wandb_init.py:init():331] wandb.init called with sweep_config: {}
config: {'epochs': 1, 'batch_size': 128, 'momentum': 0.9, 'weight_decay': 0.005, 'learning_rate': 0.01, 'optimizer': 'sgd', 'criterion': 'mse'}
2021-02-16 13:52:05,286 INFO    MainThread:23347 [wandb_init.py:init():401] starting backend
2021-02-16 13:52:05,299 INFO    MainThread:23347 [backend.py:ensure_launched():81] starting backend process...
2021-02-16 13:52:05,308 INFO    MainThread:23347 [backend.py:ensure_launched():86] started backend process with pid: 23732
2021-02-16 13:52:05,309 INFO    MainThread:23347 [wandb_init.py:init():410] backend started and connected
2021-02-16 13:52:05,311 INFO    MainThread:23347 [wandb_init.py:init():433] updated telemetry
2021-02-16 13:52:05,312 INFO    MainThread:23347 [wandb_init.py:init():456] communicating current version
2021-02-16 13:52:06,105 INFO    MainThread:23347 [wandb_init.py:init():461] got version response upgrade_message: "wandb version 0.10.19 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-02-16 13:52:06,105 INFO    MainThread:23347 [wandb_init.py:init():469] communicating run to backend with 30 second timeout
2021-02-16 13:52:06,282 INFO    MainThread:23347 [wandb_init.py:init():492] starting run threads in backend
2021-02-16 13:52:07,671 INFO    MainThread:23347 [wandb_run.py:_console_start():1411] atexit reg
2021-02-16 13:52:07,672 INFO    MainThread:23347 [wandb_run.py:_redirect():1274] redirect: SettingsConsole.REDIRECT
2021-02-16 13:52:07,674 INFO    MainThread:23347 [wandb_run.py:_redirect():1279] Redirecting console.
2021-02-16 13:52:07,674 INFO    MainThread:23347 [redirect.py:install():213] install start
2021-02-16 13:52:07,675 INFO    MainThread:23347 [redirect.py:install():228] install stop
2021-02-16 13:52:07,675 INFO    MainThread:23347 [redirect.py:install():213] install start
2021-02-16 13:52:07,675 INFO    MainThread:23347 [redirect.py:install():228] install stop
2021-02-16 13:52:07,675 INFO    MainThread:23347 [wandb_run.py:_redirect():1325] Redirects installed.
2021-02-16 13:52:07,676 INFO    MainThread:23347 [wandb_init.py:init():515] run started, returning control to user process
2021-02-16 13:52:15,104 INFO    MainThread:23347 [wandb_run.py:_atexit_cleanup():1381] got exitcode: 1
2021-02-16 13:52:15,105 INFO    MainThread:23347 [wandb_run.py:_restore():1353] restore
2021-02-16 13:52:15,106 INFO    MainThread:23347 [redirect.py:uninstall():232] uninstall start
2021-02-16 13:52:15,106 INFO    MainThread:23347 [redirect.py:_stop():287] _stop: stdout
2021-02-16 13:52:15,108 INFO    MainThread:23347 [redirect.py:_stop():293] _stop closed: stdout
2021-02-16 13:52:15,108 INFO    stdout    :23347 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-02-16 13:52:15,108 INFO    stdout    :23347 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-02-16 13:52:15,108 INFO    MainThread:23347 [redirect.py:_stop():299] _stop joined: stdout
2021-02-16 13:52:15,108 INFO    MainThread:23347 [redirect.py:_stop():301] _stop rd closed: stdout
2021-02-16 13:52:15,108 INFO    MainThread:23347 [redirect.py:uninstall():236] uninstall done
2021-02-16 13:52:15,109 INFO    MainThread:23347 [redirect.py:uninstall():232] uninstall start
2021-02-16 13:52:15,109 INFO    MainThread:23347 [redirect.py:_stop():287] _stop: stderr
2021-02-16 13:52:15,109 INFO    MainThread:23347 [redirect.py:_stop():293] _stop closed: stderr
2021-02-16 13:52:15,109 INFO    stderr    :23347 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-02-16 13:52:15,109 INFO    stderr    :23347 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-02-16 13:52:15,109 INFO    MainThread:23347 [redirect.py:_stop():299] _stop joined: stderr
2021-02-16 13:52:15,109 INFO    MainThread:23347 [redirect.py:_stop():301] _stop rd closed: stderr
2021-02-16 13:52:15,109 INFO    MainThread:23347 [redirect.py:uninstall():236] uninstall done
2021-02-16 13:52:15,255 INFO    MainThread:23347 [wandb_run.py:_wait_for_finish():1504] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 720
}

2021-02-16 13:52:17,261 INFO    MainThread:23347 [wandb_run.py:_wait_for_finish():1504] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3724
  total_bytes: 3724
}

2021-02-16 13:52:18,601 INFO    MainThread:23347 [wandb_run.py:_show_files():1726] logging synced files
