2021-02-16 16:00:15,396 INFO    MainThread:54094 [wandb_setup.py:_flush():70] setting env: {}
2021-02-16 16:00:15,396 INFO    MainThread:54094 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-16 16:00:15,396 INFO    MainThread:54094 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-16 16:00:15,396 INFO    MainThread:54094 [wandb_init.py:_log_setup():319] Logging user logs to /home/naddeok5/FIM/wandb/run-20210216_160015-1n24c9ha/logs/debug.log
2021-02-16 16:00:15,397 INFO    MainThread:54094 [wandb_init.py:_log_setup():320] Logging internal logs to /home/naddeok5/FIM/wandb/run-20210216_160015-1n24c9ha/logs/debug-internal.log
2021-02-16 16:00:15,397 INFO    MainThread:54094 [wandb_init.py:init():324] calling init triggers
2021-02-16 16:00:15,397 INFO    MainThread:54094 [wandb_init.py:init():331] wandb.init called with sweep_config: {}
config: {'epochs': 1, 'batch_size': 128, 'momentum': 0.9, 'weight_decay': 0.005, 'learning_rate': 0.01, 'optimizer': 'sgd', 'criterion': 'mse'}
2021-02-16 16:00:15,397 INFO    MainThread:54094 [wandb_init.py:init():401] starting backend
2021-02-16 16:00:15,418 INFO    MainThread:54094 [backend.py:ensure_launched():81] starting backend process...
2021-02-16 16:00:15,437 INFO    MainThread:54094 [backend.py:ensure_launched():86] started backend process with pid: 54601
2021-02-16 16:00:15,438 INFO    MainThread:54094 [wandb_init.py:init():410] backend started and connected
2021-02-16 16:00:15,441 INFO    MainThread:54094 [wandb_init.py:init():433] updated telemetry
2021-02-16 16:00:15,443 INFO    MainThread:54094 [wandb_init.py:init():456] communicating current version
2021-02-16 16:00:16,178 INFO    MainThread:54094 [wandb_init.py:init():461] got version response upgrade_message: "wandb version 0.10.19 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-02-16 16:00:16,179 INFO    MainThread:54094 [wandb_init.py:init():469] communicating run to backend with 30 second timeout
2021-02-16 16:00:16,360 INFO    MainThread:54094 [wandb_init.py:init():492] starting run threads in backend
2021-02-16 16:00:17,743 INFO    MainThread:54094 [wandb_run.py:_console_start():1411] atexit reg
2021-02-16 16:00:17,744 INFO    MainThread:54094 [wandb_run.py:_redirect():1274] redirect: SettingsConsole.REDIRECT
2021-02-16 16:00:17,745 INFO    MainThread:54094 [wandb_run.py:_redirect():1279] Redirecting console.
2021-02-16 16:00:17,745 INFO    MainThread:54094 [redirect.py:install():213] install start
2021-02-16 16:00:17,746 INFO    MainThread:54094 [redirect.py:install():228] install stop
2021-02-16 16:00:17,746 INFO    MainThread:54094 [redirect.py:install():213] install start
2021-02-16 16:00:17,746 INFO    MainThread:54094 [redirect.py:install():228] install stop
2021-02-16 16:00:17,747 INFO    MainThread:54094 [wandb_run.py:_redirect():1325] Redirects installed.
2021-02-16 16:00:17,747 INFO    MainThread:54094 [wandb_init.py:init():515] run started, returning control to user process
2021-02-16 17:50:02,890 INFO    MainThread:54094 [wandb_run.py:_atexit_cleanup():1381] got exitcode: 1
2021-02-16 17:50:02,890 INFO    MainThread:54094 [wandb_run.py:_restore():1353] restore
2021-02-16 17:50:02,891 INFO    MainThread:54094 [redirect.py:uninstall():232] uninstall start
2021-02-16 17:50:02,891 INFO    MainThread:54094 [redirect.py:_stop():287] _stop: stdout
2021-02-16 17:50:02,893 INFO    stdout    :54094 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-02-16 17:50:02,893 INFO    stdout    :54094 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-02-16 17:50:02,893 INFO    MainThread:54094 [redirect.py:_stop():293] _stop closed: stdout
2021-02-16 17:50:02,893 INFO    MainThread:54094 [redirect.py:_stop():299] _stop joined: stdout
2021-02-16 17:50:02,893 INFO    MainThread:54094 [redirect.py:_stop():301] _stop rd closed: stdout
2021-02-16 17:50:02,893 INFO    MainThread:54094 [redirect.py:uninstall():236] uninstall done
2021-02-16 17:50:02,893 INFO    MainThread:54094 [redirect.py:uninstall():232] uninstall start
2021-02-16 17:50:02,894 INFO    MainThread:54094 [redirect.py:_stop():287] _stop: stderr
2021-02-16 17:50:02,894 INFO    MainThread:54094 [redirect.py:_stop():293] _stop closed: stderr
2021-02-16 17:50:02,894 INFO    stderr    :54094 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-02-16 17:50:02,894 INFO    stderr    :54094 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-02-16 17:50:02,894 INFO    MainThread:54094 [redirect.py:_stop():299] _stop joined: stderr
2021-02-16 17:50:02,894 INFO    MainThread:54094 [redirect.py:_stop():301] _stop rd closed: stderr
2021-02-16 17:50:02,894 INFO    MainThread:54094 [redirect.py:uninstall():236] uninstall done
2021-02-16 17:50:03,029 INFO    MainThread:54094 [wandb_run.py:_wait_for_finish():1504] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 720
}

2021-02-16 17:50:05,035 INFO    MainThread:54094 [wandb_run.py:_wait_for_finish():1504] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6239
  total_bytes: 6239
}

2021-02-16 17:50:06,388 INFO    MainThread:54094 [wandb_run.py:_show_files():1726] logging synced files
